// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YmagiWebMvc.Models;

namespace YmagiWebMvc.Migrations
{
    [DbContext(typeof(YmagiWebMvcContext))]
    [Migration("20200509193816_NovasEnt")]
    partial class NovasEnt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("YmagiWebMvc.Models.Doacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<int>("Status");

                    b.Property<double>("Total");

                    b.Property<int?>("UsuarioId");

                    b.Property<int?>("VoluntarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("Doacao");
                });

            modelBuilder.Entity("YmagiWebMvc.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("Cidade");

                    b.Property<string>("Cnpj");

                    b.Property<string>("Complemento");

                    b.Property<string>("Contato");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Endereço");

                    b.Property<string>("Estado");

                    b.Property<int?>("FornecedorId");

                    b.Property<string>("NomeFantasia");

                    b.Property<int>("Numero");

                    b.Property<string>("RazaoSocial");

                    b.Property<string>("Telefone")
                        .IsRequired();

                    b.Property<int?>("VoluntarioId");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("YmagiWebMvc.Models.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int?>("InsumoId");

                    b.Property<string>("Nome");

                    b.Property<double>("Quantidade");

                    b.Property<double>("SaldoEstoque");

                    b.Property<string>("Unidade");

                    b.Property<double>("ValorTotal");

                    b.Property<double>("ValorUnit");

                    b.Property<int?>("VoluntarioId");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("Insumo");
                });

            modelBuilder.Entity("YmagiWebMvc.Models.Osc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("Cidade");

                    b.Property<string>("Complemento");

                    b.Property<string>("Contato");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Endereço");

                    b.Property<string>("Estado");

                    b.Property<string>("NomeFantasia");

                    b.Property<int>("Numero");

                    b.Property<string>("RazaoSocial");

                    b.Property<string>("Telefone")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Osc");
                });

            modelBuilder.Entity("YmagiWebMvc.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<int>("Cep");

                    b.Property<string>("Cidade");

                    b.Property<string>("Complemento");

                    b.Property<int>("Cpf");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Estado");

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome");

                    b.Property<int>("Numero");

                    b.Property<string>("Observacao");

                    b.Property<string>("Rua");

                    b.Property<int>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("YmagiWebMvc.Models.Voluntario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Celular");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("OscId");

                    b.Property<double>("Telefone");

                    b.HasKey("Id");

                    b.HasIndex("OscId");

                    b.ToTable("Voluntario");
                });

            modelBuilder.Entity("YmagiWebMvc.Models.Doacao", b =>
                {
                    b.HasOne("YmagiWebMvc.Models.Usuario", "Usuario")
                        .WithMany("Doacaos")
                        .HasForeignKey("UsuarioId");

                    b.HasOne("YmagiWebMvc.Models.Voluntario", "Voluntario")
                        .WithMany("Doacoes")
                        .HasForeignKey("VoluntarioId");
                });

            modelBuilder.Entity("YmagiWebMvc.Models.Fornecedor", b =>
                {
                    b.HasOne("YmagiWebMvc.Models.Fornecedor")
                        .WithMany("Fornecedores")
                        .HasForeignKey("FornecedorId");

                    b.HasOne("YmagiWebMvc.Models.Voluntario", "Voluntario")
                        .WithMany()
                        .HasForeignKey("VoluntarioId");
                });

            modelBuilder.Entity("YmagiWebMvc.Models.Insumo", b =>
                {
                    b.HasOne("YmagiWebMvc.Models.Insumo")
                        .WithMany("Insumos")
                        .HasForeignKey("InsumoId");

                    b.HasOne("YmagiWebMvc.Models.Voluntario")
                        .WithMany("Insumos")
                        .HasForeignKey("VoluntarioId");
                });

            modelBuilder.Entity("YmagiWebMvc.Models.Voluntario", b =>
                {
                    b.HasOne("YmagiWebMvc.Models.Osc", "Osc")
                        .WithMany("Voluntarios")
                        .HasForeignKey("OscId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
